<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hospital_Management_System.Application\Hospital_Management_System.Application.csproj" />
    <ProjectReference Include="..\Hospital_Management_System.Domain\Hospital_Management_System.Domain.csproj" />
    <ProjectReference Include="..\Hospital_Management_System.Infrastructure\Hospital_Management_System.Infrastructure.csproj" />
  </ItemGroup>

</Project>
